=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/provider.dtd
<!-- ******************************************************************* -->
<!--                                                                     -->
<!-- This DTD defines the syntax for provider XML 1.0 documents          -->
<!--                                                                     -->
<!-- Last changes:  2000-11-14                                           -->
<!--                                                                     -->
<!-- ******************************************************************* -->

<!ENTITY % InOutAttribs		"SECTION	CDATA		#IMPLIED
				 HANDLE		CDATA		#REQUIRED
				 FORCE_WRITE	(true|false)	#IMPLIED">

<!ENTITY % InOutDepAttribs	"PROPERTY	CDATA	#REQUIRED">



<!-- ************************************* -->
<!--  Root element                         -->
<!-- ************************************* -->

<!ELEMENT PAULA_CONFIG (DEFINITIONS*,
			PROPERTY*,KEYBINDINGS*,INSTANCE*,SECTION*,HANDLE*)>


<!-- ****************************************** -->
<!--  DEFINITIONS and its elements              -->
<!-- ****************************************** -->

<!ELEMENT DEFINITIONS ((DEFINE)*)>

<!ELEMENT DEFINE (#PCDATA)>
<!ATTLIST DEFINE
	NAME		CDATA		#REQUIRED
>



<!-- ****************************************** -->
<!--  PROPERTY, KEYBINDINGS and their elements  -->
<!-- ****************************************** -->

<!ELEMENT PROPERTY (DEPENDENCIES?,(IN|OUT|INOUT)*)>
<!ATTLIST PROPERTY 
	ID		CDATA		#REQUIRED
	MIGHT_BE_NULL	(true|false)	#IMPLIED
>


<!ELEMENT KEYBINDINGS ((IN|OUT|INOUT)*)>



<!ELEMENT DEPENDENCIES (IN_DEP|OUT_DEP|INOUT_DEP)*>

<!ELEMENT IN_DEP EMPTY>
<!ATTLIST IN_DEP
	%InOutDepAttribs;
>

<!ELEMENT OUT_DEP EMPTY>
<!ATTLIST OUT_DEP
	%InOutDepAttribs;
>

<!ELEMENT INOUT_DEP EMPTY>
<!ATTLIST INOUT_DEP
	%InOutDepAttribs;
>


<!-- ************************************* -->
<!--  IN/OUT/INOUT and their elements      -->
<!-- ************************************* -->

<!ELEMENT IN	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (REGEXP|FUNCTION|INTERNAL)?,
		 (CALL)?)>
<!ATTLIST IN
	%InOutAttribs;
>
<!ELEMENT OUT	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (REGEXP|FUNCTION)?,
		 (CALL)?)>
<!ATTLIST OUT
	%InOutAttribs;
>
<!ELEMENT INOUT	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (FUNCTION|REGEXP)?,
		 (CALL)?)>
<!ATTLIST INOUT
	%InOutAttribs;
>


<!ELEMENT FUNCTION EMPTY>

<!ELEMENT INTERNAL (#PCDATA)>

<!ELEMENT REGEXP (#PCDATA)>
<!ATTLIST REGEXP
	MODIFIERS	CDATA	#IMPLIED
>



<!ELEMENT REQUIRED_ASSIGNMENT EMPTY>

<!ELEMENT OPTIONAL_ASSIGNMENT EMPTY>
<!ATTLIST OPTIONAL_ASSIGNMENT
	DEFAULT			CDATA		#IMPLIED
	TEXT			CDATA		#IMPLIED
	DELETE_IF_DEFAULT	(true|false)	#IMPLIED
>

<!ELEMENT FLAG EMPTY>
<!ATTLIST FLAG
	DEFAULT			CDATA		#IMPLIED
	VALUE			CDATA		#IMPLIED
	TEXT			CDATA		#IMPLIED
>


<!-- ************************************* -->
<!--  SECTION and its elements             -->
<!-- ************************************* -->

<!ELEMENT SECTION (REGEXP,ERROR_NOT_FOUND?)>
<!ATTLIST SECTION
	ID	CDATA	#REQUIRED
>

<!ELEMENT ERROR_NOT_FOUND EMPTY>
<!ATTLIST ERROR_NOT_FOUND
	CODE	CDATA	#REQUIRED
>




<!-- ************************************* -->
<!--  HANDLE and its elements              -->
<!-- ************************************* -->

<!ELEMENT HANDLE (WHITESPACE?,COMMENTS?,REMOVE?,ERROR?,PERMISSIONS?)>
<!ATTLIST HANDLE
	ID	CDATA			#REQUIRED
	NO	CDATA			#REQUIRED
	TYPE	(FILE|COMMAND|DUMMY)	#REQUIRED
	ACCESS	(R|W|RW)		#REQUIRED
	NAME	CDATA			#IMPLIED
>

<!ELEMENT CALL EMPTY>
<!ATTLIST CALL
	OPTION	CDATA		#IMPLIED
>

<!ELEMENT WHITESPACE EMPTY>
<!ATTLIST WHITESPACE
	WRITE	CDATA		#REQUIRED
>

<!ELEMENT COMMENTS (READ.LINE,WRITE.LINE)>

<!ELEMENT READ.LINE (#PCDATA)>
<!ELEMENT WRITE.LINE (#PCDATA)>


<!ELEMENT REMOVE EMPTY>
<!ATTLIST REMOVE
	IF_EMPTY	(true|false)	#IMPLIED
>

<!ELEMENT ERROR EMPTY>
<!ATTLIST ERROR
	ONREAD		(true|false)	#IMPLIED
	ONWRITE		(true|false)	#IMPLIED
>

<!ELEMENT PERMISSIONS EMPTY>
<!ATTLIST PERMISSIONS
	UMASK		CDATA	#IMPLIED
	UID		CDATA	#IMPLIED
	GID		CDATA	#IMPLIED
>

=== durandom/b4wbem/WebFrontend/CIMOM/lib/PaulA/Provider/paul/PaulA_WWWFilter.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY blocklist           "/etc/junkbuster/blocklist.local"       >
<!ENTITY forward             "/etc/junkbuster/forward"               >
<!ENTITY squid.conf          "/etc/squid/squid.conf"                 >
<!ENTITY junkbuster_status   "/etc/rc.d/init.d/junkbuster status |"  >
<!ENTITY chkconfig_status    "chkconfig --list junkbuster |"         >
<!ENTITY junkbuster_switch   "| /etc/rc.d/init.d/junkbuster"         > 
<!ENTITY chkconfig_switch    "| chkconfig"                           >
<!ENTITY squid_restart       "| /etc/rc.d/init.d/squid restart"      >
<!ENTITY download_blocklist  "/usr/bin/junkbuster_update"            >

]>

<PAULA_CONFIG>

  <!-- ********************* -->
  <!-- **** DEFINITIONS **** -->
  <!-- ********************* -->

  <DEFINITIONS>
    <DEFINE NAME="download_blocklist">&download_blocklist;</DEFINE>
  </DEFINITIONS>


  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- ************************ -->
  <PROPERTY ID="FilterEnabled">
    <IN HANDLE="junkbuster_status">
      <FLAG DEFAULT="0"
	    VALUE="1" />
      <REGEXP MODIFIERS="ms">(.*)(running)(.*)</REGEXP>
    </IN>
    <IN HANDLE="chkconfig_status">
      <FLAG DEFAULT="0"
	    VALUE="1" />
      <REGEXP MODIFIERS="ms">(.*)(on)(.*)</REGEXP>
    </IN>
    <INOUT HANDLE="forward">
      <FLAG DEFAULT="0"
	    VALUE="1" 
            TEXT="\*\t\tlocalhost:3129\t.\t.\n"/>
      <REGEXP MODIFIERS="ms">(.*)(\*\s+localhost:3129\s+.\s+.\n)(.*)</REGEXP>
    </INOUT>
    <INOUT HANDLE="squid.conf">
      <FLAG DEFAULT="0"
	    VALUE="1" 
            TEXT="http_port\t3129\n" />
      <REGEXP MODIFIERS="ms">(.*)(^http_port\s+3129\n)(.*)</REGEXP>
    </INOUT>
    <OUT HANDLE="junkbuster_switch"> 
       <FUNCTION/> 
    </OUT> 
    <OUT HANDLE="chkconfig_switch"> 
       <FUNCTION/> 
    </OUT> 
    <OUT HANDLE="squid_restart"> 
    </OUT> 
  </PROPERTY>


  <!-- *************** -->
  <PROPERTY ID="BlockList"
	    MIGHT_BE_NULL="true">
    <IN HANDLE="blocklist">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/> 
    </IN>
    <OUT HANDLE="blocklist">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/> 
    </OUT>
  </PROPERTY>

  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="blocklist"            NO="1"      TYPE="FILE"       ACCESS="RW"
	  NAME="&blocklist;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="forward"              NO="2"      TYPE="FILE"       ACCESS="RW"
	  NAME="&forward;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="junkbuster_status"    NO="3"     TYPE="COMMAND"     ACCESS="R"
	NAME="&junkbuster_status;">
  </HANDLE>

  <HANDLE ID="chkconfig_status"     NO="4"     TYPE="COMMAND"     ACCESS="R"
	NAME="&chkconfig_status;">
  </HANDLE>

  <HANDLE ID="junkbuster_switch"    NO="5"     TYPE="COMMAND"     ACCESS="W"
	NAME="&junkbuster_switch;">
  </HANDLE>

  <HANDLE ID="chkconfig_switch"     NO="6"     TYPE="COMMAND"     ACCESS="W"
	NAME="&chkconfig_switch;">
  </HANDLE>

  <HANDLE ID="squid.conf"           NO="7"     TYPE="FILE"        ACCESS="RW"
	  NAME="&squid.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="squid_restart"        NO="8"     TYPE="COMMAND"     ACCESS="W"
	NAME="&squid_restart;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/CIMOM/lib/PaulA/Provider/test/PaulA_MTA.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY aliases          "files/postfix/aliases"        >
<!ENTITY dlists           "files/postfix/dlists.virtual" >
<!ENTITY main.cf          "files/postfix/main.cf"        >
<!ENTITY virtual          "files/postfix/virtual"        >
<!ENTITY postmap_dlists   "| postmap.sh dlists.virtual"  >
<!ENTITY postmap_aliases  "| postmap.sh aliases"         >
<!ENTITY postmap_virtual  "| postmap.sh virtual"         >
<!ENTITY postfix_reload   "| postmap.sh reload"          >
<!ENTITY perl             "| perl"                       >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->


  <!-- **************************** -->
  <PROPERTY ID="ValidDistributionLists"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="dlists">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="postmap_dlists">
    </OUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- ******************* -->
  <PROPERTY ID="MailAliasRoot"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="aliases">
      <OPTIONAL_ASSIGNMENT
                            TEXT="root:\t$VAR\n"
                            DELETE_IF_DEFAULT="true"/>
      <REGEXP MODIFIERS="ms">.*^(root:[^\n\S]+(\S+)\n)$.*</REGEXP>
    </INOUT>
    <OUT HANDLE="postmap_aliases">
    </OUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- ************************** -->
  <PROPERTY ID="MailAliasPostmaster">
    <INOUT HANDLE="aliases">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*^postmaster:[^\n\S]+)(\S+)($.*)</REGEXP>
    </INOUT>
    <OUT HANDLE="postmap_aliases">
    </OUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- ************************** -->
  <PROPERTY ID="MailAliasFaxmaster">
    <INOUT HANDLE="aliases">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*^faxmaster:[^\n\S]+)(\S+)($.*)</REGEXP>
    </INOUT>
    <OUT HANDLE="postmap_aliases">
    </OUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="MyDomain">
    <INOUT HANDLE="main.cf">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*^mydomain\s*=\s*)(\S+)($.*)</REGEXP>
    </INOUT>
    <OUT HANDLE="perl">
    </OUT>
    <OUT HANDLE="postmap_virtual">
    </OUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="RelayHost"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="main.cf">
      <OPTIONAL_ASSIGNMENT TEXT="relayhost = [$VAR]\n"
			   DELETE_IF_DEFAULT="true" />
      <REGEXP MODIFIERS="ms">.*^(relayhost\s*=\s*\[?([^\]\s]+)\]?)$.*</REGEXP>
    </INOUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->



  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="dlists"           NO="1"      TYPE="FILE"        ACCESS="RW"
        NAME="&dlists;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="postmap_dlists"   NO="2"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postmap_dlists;">
  </HANDLE>

  <HANDLE ID="aliases"          NO="3"      TYPE="FILE"        ACCESS="RW"
	  NAME="&aliases;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="postmap_aliases"  NO="4"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postmap_aliases;">
  </HANDLE>

  <HANDLE ID="main.cf"          NO="5"      TYPE="FILE"        ACCESS="RW"
	  NAME="&main.cf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="virtual"          NO="6"      TYPE="FILE"        ACCESS="RW"
	  NAME="&virtual;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="perl"             NO="7"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&perl;">
  </HANDLE>

  <HANDLE ID="postmap_virtual"  NO="8"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postmap_virtual;">
  </HANDLE>

  <HANDLE ID="postfix_reload"   NO="9"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postfix_reload;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/paul/PaulA_System.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY shells         "/etc/shells"                              >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- *********************** -->
  <PROPERTY ID="ValidLoginShells">
    <INOUT HANDLE="shells">
      <FUNCTION/>
    </INOUT>
  </PROPERTY>



  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->



  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="shells"            NO="3"      TYPE="FILE"        ACCESS="RW"
	  NAME="&shells;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>


</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/CIMOM/lib/PaulA/Provider/paul/PaulA_Mail.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY pcron.conf         "???/pcron.conf"                >
<!ENTITY ip-up              "/etc/ppp/ip-up.local"          >
<!ENTITY fetchmailrc        "/root/.fetchmailrc"            >

]>

<PAULA_CONFIG>

  <!-- ********************* -->
  <!-- **** DEFINITIONS **** -->
  <!-- ********************* -->

  <DEFINITIONS>
    <DEFINE NAME="fetchmailrc">&fetchmailrc;</DEFINE>
  </DEFINITIONS>


  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->


  <!-- *********************** -->
  <PROPERTY ID="MailWeekdaysStart"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="MailWeekdaysEnd" />
      <IN_DEP PROPERTY="MailWeekdaysInterval" />
      <OUT_DEP PROPERTY="MailWeekdaysEnd" />
      <OUT_DEP PROPERTY="MailWeekdaysInterval" />
    </DEPENDENCIES>
    <IN HANDLE="pcron.conf">
      <OPTIONAL_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">.*^(fetchmail.*?;m\d+Wk(\d+)-\d+\s*)</REGEXP>
    </IN>
  </PROPERTY>

  <!-- ********************* -->
  <PROPERTY ID="MailWeekdaysEnd"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="MailWeekdaysStart" />
      <IN_DEP PROPERTY="MailWeekdaysInterval" />
      <OUT_DEP PROPERTY="MailWeekdaysStart" />
      <OUT_DEP PROPERTY="MailWeekdaysInterval" />
    </DEPENDENCIES>
    <IN HANDLE="pcron.conf">
      <OPTIONAL_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">.*?^(fetchmail.*?;m\d+Wk\d+-(\d+)\s*)</REGEXP>
    </IN>
  </PROPERTY>

  <!-- ************************** -->
  <PROPERTY ID="MailWeekdaysInterval" 
            MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="MailWeekdaysStart" />
      <IN_DEP PROPERTY="MailWeekdaysEnd" />
      <OUT_DEP PROPERTY="MailWeekdaysStart" />
      <OUT_DEP PROPERTY="MailWeekdaysEnd" />
    </DEPENDENCIES>
    <IN HANDLE="pcron.conf">
      <OPTIONAL_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">.*?^(fetchmail.*?;m(\d+)Wk\d+-\d+\s*)</REGEXP>
    </IN>
    <OUT HANDLE="pcron.conf" FORCE_WRITE="true">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </OUT>
  </PROPERTY>


  <!-- ********************** -->
  <PROPERTY ID="MailWeekendStart"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="MailWeekendEnd" />
      <IN_DEP PROPERTY="MailWeekendInterval" />
      <OUT_DEP PROPERTY="MailWeekendEnd" />
      <OUT_DEP PROPERTY="MailWeekendInterval" />
    </DEPENDENCIES>
    <IN HANDLE="pcron.conf">
      <OPTIONAL_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">.*^(fetchmail.*?;m\d+Wd(\d+)-\d+)$</REGEXP>
    </IN>
  </PROPERTY>

  <!-- ******************** -->
  <PROPERTY ID="MailWeekendEnd"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="MailWeekendStart" />
      <IN_DEP PROPERTY="MailWeekendInterval" />
      <OUT_DEP PROPERTY="MailWeekendStart" />
      <OUT_DEP PROPERTY="MailWeekendInterval" />
    </DEPENDENCIES>
    <IN HANDLE="pcron.conf">
      <OPTIONAL_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">.*^(fetchmail.*?;m\d+Wd\d+-(\d+))$</REGEXP>
    </IN>
  </PROPERTY>

  <!-- ************************* -->
  <PROPERTY ID="MailWeekendInterval" 
            MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="MailWeekendStart" />
      <IN_DEP PROPERTY="MailWeekendEnd" />
      <OUT_DEP PROPERTY="MailWeekendStart" />
      <OUT_DEP PROPERTY="MailWeekendEnd" />
    </DEPENDENCIES>
    <IN HANDLE="pcron.conf">
      <OPTIONAL_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">.*^(fetchmail.*?;m(\d+)Wd\d+-\d+)$</REGEXP>
    </IN>
    <OUT HANDLE="pcron.conf" FORCE_WRITE="true">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </OUT>
  </PROPERTY>


  <!-- ************************* -->
  <PROPERTY ID="FetchMailsOnDialUp">
    <INOUT HANDLE="ip-up">
      <FLAG DEFAULT="0"
	    VALUE="1"
	    TEXT="fetchmail -f &fetchmailrc;\n"/>
      <REGEXP MODIFIERS="ms">(.*^)(fetchmail -f &fetchmailrc;\n)($.*)</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->



  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="pcron.conf"           NO="1"      TYPE="FILE"        ACCESS="RW"
        NAME="&pcron.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="ip-up"                NO="2"      TYPE="FILE"        ACCESS="RW"
        NAME="&ip-up;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->
