=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/provider.dtd
<!-- ******************************************************************* -->
<!--                                                                     -->
<!-- This DTD defines the syntax for provider XML 1.0 documents          -->
<!--                                                                     -->
<!-- Last changes:  2000-11-14                                           -->
<!--                                                                     -->
<!-- ******************************************************************* -->

<!ENTITY % InOutAttribs		"SECTION	CDATA		#IMPLIED
				 HANDLE		CDATA		#REQUIRED
				 FORCE_WRITE	(true|false)	#IMPLIED">

<!ENTITY % InOutDepAttribs	"PROPERTY	CDATA	#REQUIRED">



<!-- ************************************* -->
<!--  Root element                         -->
<!-- ************************************* -->

<!ELEMENT PAULA_CONFIG (DEFINITIONS*,
			PROPERTY*,KEYBINDINGS*,INSTANCE*,SECTION*,HANDLE*)>


<!-- ****************************************** -->
<!--  DEFINITIONS and its elements              -->
<!-- ****************************************** -->

<!ELEMENT DEFINITIONS ((DEFINE)*)>

<!ELEMENT DEFINE (#PCDATA)>
<!ATTLIST DEFINE
	NAME		CDATA		#REQUIRED
>



<!-- ****************************************** -->
<!--  PROPERTY, KEYBINDINGS and their elements  -->
<!-- ****************************************** -->

<!ELEMENT PROPERTY (DEPENDENCIES?,(IN|OUT|INOUT)*)>
<!ATTLIST PROPERTY 
	ID		CDATA		#REQUIRED
	MIGHT_BE_NULL	(true|false)	#IMPLIED
>


<!ELEMENT KEYBINDINGS ((IN|OUT|INOUT)*)>



<!ELEMENT DEPENDENCIES (IN_DEP|OUT_DEP|INOUT_DEP)*>

<!ELEMENT IN_DEP EMPTY>
<!ATTLIST IN_DEP
	%InOutDepAttribs;
>

<!ELEMENT OUT_DEP EMPTY>
<!ATTLIST OUT_DEP
	%InOutDepAttribs;
>

<!ELEMENT INOUT_DEP EMPTY>
<!ATTLIST INOUT_DEP
	%InOutDepAttribs;
>


<!-- ************************************* -->
<!--  IN/OUT/INOUT and their elements      -->
<!-- ************************************* -->

<!ELEMENT IN	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (REGEXP|FUNCTION|INTERNAL)?,
		 (CALL)?)>
<!ATTLIST IN
	%InOutAttribs;
>
<!ELEMENT OUT	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (REGEXP|FUNCTION)?,
		 (CALL)?)>
<!ATTLIST OUT
	%InOutAttribs;
>
<!ELEMENT INOUT	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (FUNCTION|REGEXP)?,
		 (CALL)?)>
<!ATTLIST INOUT
	%InOutAttribs;
>


<!ELEMENT FUNCTION EMPTY>

<!ELEMENT INTERNAL (#PCDATA)>

<!ELEMENT REGEXP (#PCDATA)>
<!ATTLIST REGEXP
	MODIFIERS	CDATA	#IMPLIED
>



<!ELEMENT REQUIRED_ASSIGNMENT EMPTY>

<!ELEMENT OPTIONAL_ASSIGNMENT EMPTY>
<!ATTLIST OPTIONAL_ASSIGNMENT
	DEFAULT			CDATA		#IMPLIED
	TEXT			CDATA		#IMPLIED
	DELETE_IF_DEFAULT	(true|false)	#IMPLIED
>

<!ELEMENT FLAG EMPTY>
<!ATTLIST FLAG
	DEFAULT			CDATA		#IMPLIED
	VALUE			CDATA		#IMPLIED
	TEXT			CDATA		#IMPLIED
>


<!-- ************************************* -->
<!--  SECTION and its elements             -->
<!-- ************************************* -->

<!ELEMENT SECTION (REGEXP,ERROR_NOT_FOUND?)>
<!ATTLIST SECTION
	ID	CDATA	#REQUIRED
>

<!ELEMENT ERROR_NOT_FOUND EMPTY>
<!ATTLIST ERROR_NOT_FOUND
	CODE	CDATA	#REQUIRED
>




<!-- ************************************* -->
<!--  HANDLE and its elements              -->
<!-- ************************************* -->

<!ELEMENT HANDLE (WHITESPACE?,COMMENTS?,REMOVE?,ERROR?,PERMISSIONS?)>
<!ATTLIST HANDLE
	ID	CDATA			#REQUIRED
	NO	CDATA			#REQUIRED
	TYPE	(FILE|COMMAND|DUMMY)	#REQUIRED
	ACCESS	(R|W|RW)		#REQUIRED
	NAME	CDATA			#IMPLIED
>

<!ELEMENT CALL EMPTY>
<!ATTLIST CALL
	OPTION	CDATA		#IMPLIED
>

<!ELEMENT WHITESPACE EMPTY>
<!ATTLIST WHITESPACE
	WRITE	CDATA		#REQUIRED
>

<!ELEMENT COMMENTS (READ.LINE,WRITE.LINE)>

<!ELEMENT READ.LINE (#PCDATA)>
<!ELEMENT WRITE.LINE (#PCDATA)>


<!ELEMENT REMOVE EMPTY>
<!ATTLIST REMOVE
	IF_EMPTY	(true|false)	#IMPLIED
>

<!ELEMENT ERROR EMPTY>
<!ATTLIST ERROR
	ONREAD		(true|false)	#IMPLIED
	ONWRITE		(true|false)	#IMPLIED
>

<!ELEMENT PERMISSIONS EMPTY>
<!ATTLIST PERMISSIONS
	UMASK		CDATA	#IMPLIED
	UID		CDATA	#IMPLIED
	GID		CDATA	#IMPLIED
>

=== durandom/b4wbem/CIMOM/CIMOM/lib/PaulA/Provider/paul/PaulA_Fax.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY config.faxCAPI     "/var/spool/fax/etc/config.faxCAPI" >
<!ENTITY capircvd.conf      "/etc/capircvd/capircvd.conf"       >
<!ENTITY aliases            "/etc/postfix/aliases"              >
<!ENTITY inittab            "/etc/inittab"                      >
<!ENTITY postmap_aliases    "| postmap aliases"                 >
<!ENTITY hup_init           "| killall -HUP init"               >
<!ENTITY kill_capircvd      "| killall -9 capircvd"             >
<!ENTITY kill_c2faxrecv     "| killall -9 c2faxrecv"            >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- ***************** -->
  <PROPERTY ID="FaxEnabled">
    <INOUT HANDLE="inittab">
      <FLAG DEFAULT="0"
            VALUE="1" 
            TEXT="capi:2345:respawn:/usr/sbin/capircvd -D 1 -L /var/log/capirvd\n"/>
            <REGEXP MODIFIERS="ms">(.*^)(capi:2345:respawn:/usr/sbin/capircvd -D 1 -L /var/log/capirvd)($.*)</REGEXP>
    </INOUT>
    <INOUT HANDLE="inittab">
      <FLAG DEFAULT="0"
            VALUE="1" 
            TEXT="fr:2345:respawn:/usr/local/bin/c2faxrecv\n"/>
            <REGEXP MODIFIERS="ms">(.*^)(fr:2345:respawn:/usr/local/bin/c2faxrecv)($.*)</REGEXP>
    </INOUT>
    <OUT HANDLE="kill_capircvd">
    </OUT>
    <OUT HANDLE="kill_c2faxrecv">
    </OUT>
    <OUT HANDLE="hup_init">
    </OUT>
  </PROPERTY>

  <!-- ******************** -->
  <PROPERTY ID="HeaderIDString"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="config.faxCAPI">
      <OPTIONAL_ASSIGNMENT 
                           TEXT="LocalIdentifier: $VAR\n"
			   DELETE_IF_DEFAULT="true" />
      <REGEXP MODIFIERS="ms">.*(^LocalIdentifier:\s+(.+?)\s*\n).*</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ********************* -->
  <PROPERTY ID="HeaderFaxNumber"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="config.faxCAPI">
      <OPTIONAL_ASSIGNMENT
                           TEXT="FAXNumber: $VAR\n"
			   DELETE_IF_DEFAULT="true" />
      <REGEXP MODIFIERS="ms">.*(^FAXNumber:\s+(.+?)\s*\n).*</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ************************ -->
  <PROPERTY ID="DefaultMailForward"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="aliases">
      <OPTIONAL_ASSIGNMENT
                            TEXT="fax_default:\t$VAR\n"
                            DELETE_IF_DEFAULT="true"/>
      <REGEXP MODIFIERS="ms">.*^(fax_default:[^\n\S]+(\S+)\n)$.*</REGEXP>
    </INOUT>
    <OUT HANDLE="postmap_aliases">
    </OUT>
  </PROPERTY>

  <!-- ***************** -->
  <PROPERTY ID="CountryCode"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="Prefix" />
    </DEPENDENCIES>
    <INOUT SECTION="global" HANDLE="capircvd.conf">
      <OPTIONAL_ASSIGNMENT
                            TEXT="iprefix\t$VAR"
                            DELETE_IF_DEFAULT="true"/>
      <REGEXP MODIFIERS="ms">.*^(iprefix[^\n\S]+(\d+))$.*</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ************** -->
  <PROPERTY ID="AreaCode"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="Prefix" />
    </DEPENDENCIES>
    <INOUT SECTION="global" HANDLE="capircvd.conf">
      <OPTIONAL_ASSIGNMENT
                            TEXT="nprefix\t$VAR"
                            DELETE_IF_DEFAULT="true"/>
      <REGEXP MODIFIERS="ms">.*^(nprefix[^\n\S]+(\d+))$.*</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- **************** -->
  <PROPERTY ID="BaseNumber"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="CountryCode"/>
      <IN_DEP PROPERTY="AreaCode" />
      <INOUT_DEP PROPERTY="Prefix" />
    </DEPENDENCIES>
    <IN SECTION="controller" HANDLE="capircvd.conf2">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </IN>
    <OUT HANDLE="dummy">
      <!-- otherwise additionalOutStuff wouldn't be done -->
    </OUT>
  </PROPERTY>

  <!-- ************ -->
  <PROPERTY ID="Prefix"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="AreaCode" />
      <IN_DEP PROPERTY="CountryCode" />
      <IN_DEP PROPERTY="BaseNumber" />
      <INOUT_DEP PROPERTY="ValidFaxExtensions" />
      <INOUT_DEP PROPERTY="NumLength" />
    </DEPENDENCIES>
    <INOUT SECTION="controller" HANDLE="capircvd.conf3">
      <OPTIONAL_ASSIGNMENT
                            TEXT="prefix\t$VAR"
                            DELETE_IF_DEFAULT="true"/>
      <REGEXP MODIFIERS="ms">.*^(prefix[^\n\S]+(\d+))$.*</REGEXP>
    </INOUT>
    <!-- Because Prefix shouldn't be changed directly, there's no
    additionalOutStuff function -->
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="NumLength"
	    MIGHT_BE_NULL="true">
    <INOUT SECTION="controller" HANDLE="capircvd.conf5">
      <OPTIONAL_ASSIGNMENT  
                            TEXT="numlength\t$VAR"
                            DELETE_IF_DEFAULT="true"/>
      <REGEXP MODIFIERS="ms">.*^(numlength[^\n\S]+(\d+))$.*</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ************************ -->
  <PROPERTY ID="ValidFaxExtensions"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="Prefix" />
      <INOUT_DEP PROPERTY="NumLength" />
    </DEPENDENCIES>
    <IN HANDLE="capircvd.conf4">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </IN>
    <OUT HANDLE="capircvd.conf4" FORCE_WRITE="true">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </OUT>
  </PROPERTY>


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="global">
    <REGEXP MODIFIERS="ms">(.*^)(=global\n.*?\n)(\n.*)</REGEXP>
  </SECTION>

  <SECTION ID="controller">
    <REGEXP MODIFIERS="ms">(.*^)(=controller1\n.*?\n)(\n.*)</REGEXP>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="config.faxCAPI"       NO="1"      TYPE="FILE"     ACCESS="RW"
          NAME="&config.faxCAPI;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="capircvd.conf"        NO="2"      TYPE="FILE"     ACCESS="RW"
	  NAME="&capircvd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="capircvd.conf2"       NO="3"      TYPE="FILE"     ACCESS="RW"
	  NAME="&capircvd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="dummy"                NO="4"      TYPE="DUMMY"    ACCESS="W">
  </HANDLE>

  <HANDLE ID="capircvd.conf3"       NO="5"      TYPE="FILE"     ACCESS="RW"
	  NAME="&capircvd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="capircvd.conf4"       NO="6"      TYPE="FILE"     ACCESS="RW"
	  NAME="&capircvd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="capircvd.conf5"       NO="7"      TYPE="FILE"     ACCESS="RW"
	  NAME="&capircvd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="aliases"              NO="8"      TYPE="FILE"     ACCESS="RW"
	  NAME="&aliases;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="postmap_aliases"      NO="9"      TYPE="COMMAND"  ACCESS="W"
	  NAME="&postmap_aliases;">
  </HANDLE>

  <HANDLE ID="inittab"              NO="10"     TYPE="FILE"     ACCESS="RW"
	  NAME="&inittab;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="kill_capircvd"        NO="11"     TYPE="COMMAND"     ACCESS="W"
	  NAME="&kill_capircvd;">
    <ERROR ONWRITE="false"/>
  </HANDLE>

  <HANDLE ID="kill_c2faxrecv"       NO="12"     TYPE="COMMAND"     ACCESS="W"
	  NAME="&kill_c2faxrecv;">
    <ERROR ONWRITE="false"/>
  </HANDLE>

  <HANDLE ID="hup_init"             NO="13"     TYPE="COMMAND"     ACCESS="W"
	  NAME="&hup_init;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/CIMOM/lib/PaulA/Provider/test/Test_System.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY xf86config      "files/XF86Config"                >
<!ENTITY dateout         "| setdate.sh"                    >
<!ENTITY datein          "date +&#37;H:&#37;M:&#37;S |"    >
<!ENTITY virtual         "files/postfix/virtual"           >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- *********************** -->
  <PROPERTY ID="KeyboardProtocol">

    <INOUT SECTION="keyboard" HANDLE="xf86config">
      <OPTIONAL_ASSIGNMENT DEFAULT="DefaultProtocol"
			   TEXT="\tProtocol=&quot;$VAR&quot;\n"
			   DELETE_IF_DEFAULT="false"/>
      <REGEXP>.*\s(Protocol\s+"(.*?)")\s.*</REGEXP>
    </INOUT>

  </PROPERTY>

  <!-- ****************** -->
  <PROPERTY ID="MouseDevice">

    <INOUT SECTION="pointer"
	   HANDLE="xf86config">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP>(.*Device\s+")(.+?)(".*)</REGEXP>
    </INOUT>

  </PROPERTY>


  <!-- ********************** -->
  <PROPERTY ID="Emulate3Buttons">

    <INOUT SECTION="pointer" HANDLE="xf86config">
      <FLAG DEFAULT="0"
	    VALUE="1"
	    TEXT="\tEmulate3Buttons\n"/>
      <REGEXP>(.*\s)(Emulate3Buttons)(\s.*)</REGEXP>
    </INOUT>

  </PROPERTY>


  <!-- **************** -->
  <PROPERTY ID="LocalTime">
    
    <IN HANDLE="datein">
      <REGEXP MODIFIERS="m">^()(.*)()$</REGEXP>
    </IN>

    <OUT HANDLE="dateout">
      <CALL OPTION="$VAR"/>
    </OUT>

  </PROPERTY>

  <!-- ********************* -->
  <PROPERTY ID="VirtualDomains">
    
    <IN HANDLE="virtual">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </IN>

  </PROPERTY>


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="keyboard">
    <REGEXP MODIFIERS="s">(.*\sSection\s+"Keyboard")(.+?)(EndSection\s.*)</REGEXP>
  </SECTION>

  <SECTION ID="pointer">
    <REGEXP MODIFIERS="s">(.*\sSection\s+"Pointer")(.+?)(EndSection\s.*)</REGEXP>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="xf86config"        NO="1"      TYPE="FILE"        ACCESS="RW"
	  NAME="&xf86config;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="datein"            NO="4"      TYPE="COMMAND"     ACCESS="R"
	  NAME="&datein;">
  </HANDLE>

  <HANDLE ID="dateout"           NO="5"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&dateout;">
  </HANDLE>

  <HANDLE ID="virtual"           NO="7"      TYPE="FILE"        ACCESS="RW"
	  NAME="&virtual;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/WebFrontend/CIMOM/lib/PaulA/Provider/test/PaulA_VPN.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY vpnd.conf          "files/vpnd.conf"            >
<!ENTITY ifconfig           "ifconfig.sh |"              >
<!ENTITY chkconfig_status   "chkconfig.sh --list vpnd |" >
<!ENTITY vpnd_status        "vpnd.sh status |"           >
<!ENTITY vpnd_switch        "| vpnd.sh"                  >
<!ENTITY chkconfig_switch   "| chkconfig.sh"             >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->


  <!-- *************** -->
  <PROPERTY ID="ServerIP">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="VPNEnabled" />
      <INOUT_DEP PROPERTY="ServerPort" />
    </DEPENDENCIES>
    
    <INOUT HANDLE="vpnd.conf">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*^server[^\S\n]+)((?:\d+\.\S+)*)(.*)</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ***************** -->
  <PROPERTY ID="ServerPort">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="VPNEnabled" />
    </DEPENDENCIES>
    
    <INOUT HANDLE="vpnd.conf2">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*^server[^\n\S]+?\S*(?:\d+\.\S+)*[^\n\S]*)(\S*)($.*)</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ************* -->
  <PROPERTY ID="Remote">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="RouteLocalNetwork" />
      <INOUT_DEP PROPERTY="VPNEnabled" />
    </DEPENDENCIES>
    
    <INOUT HANDLE="vpnd.conf">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*^remote[^\n\S]+)(\S*)$.*</REGEXP>
    </INOUT>
    <OUT HANDLE="vpnd.conf">
      <FUNCTION/>
    </OUT>
  </PROPERTY>

  <!-- ************ -->
  <PROPERTY ID="Local">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="VPNEnabled" />
    </DEPENDENCIES>
    
    <INOUT HANDLE="vpnd.conf">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP  MODIFIERS="ms">(.*^local[^\n\S]+)(\S*)$.*</REGEXP>
    </INOUT>
  </PROPERTY>
  
  <!-- *************** -->
  <PROPERTY ID="IsServer">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="VPNEnabled" />
    </DEPENDENCIES>
    
    <INOUT HANDLE="vpnd.conf">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>
  
  <!-- ************************ -->
  <PROPERTY ID="RouteLocalNetwork">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="Remote" />
      <IN_DEP PROPERTY="InetAddr" />
      <IN_DEP PROPERTY="Mask" />
      <INOUT_DEP PROPERTY="VPNEnabled" />
    </DEPENDENCIES>
    
    <IN HANDLE="vpnd.conf">
      <FLAG DEFAULT="0"
            VALUE="1" />
      <REGEXP MODIFIERS="ms">(.*^)(route1\s.*?$).*</REGEXP>
    </IN>
    <OUT HANDLE="vpnd.conf" FORCE_WRITE="true">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </OUT>
  </PROPERTY>

  <!-- ***************** -->
  <PROPERTY ID="VPNEnabled">
    <IN HANDLE="vpnd_status">
      <FLAG DEFAULT="0"
	    VALUE="1" />
      <REGEXP MODIFIERS="ms">(.*)(is running)(.*)</REGEXP>
    </IN>
    <IN HANDLE="chkconfig_status">
      <FLAG DEFAULT="0"
	    VALUE="1" />
      <REGEXP MODIFIERS="ms">(.*)(on)(.*)</REGEXP>
    </IN>
    <OUT HANDLE="vpnd_switch">
       <FUNCTION/>
    </OUT>
    <OUT HANDLE="chkconfig_switch">
       <FUNCTION/>
    </OUT>
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="InetAddr">
    <IN SECTION="eth0" HANDLE="ifconfig">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP MODIFIERS="ms">(.*\binet addr:)(\S+).*</REGEXP>
    </IN>
  </PROPERTY>

  <!-- *********** -->
  <PROPERTY ID="Mask">
    <IN SECTION="eth0" HANDLE="ifconfig">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP  MODIFIERS="ms">(.*\bMask:)(\S+).*</REGEXP>
    </IN>
  </PROPERTY>


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="eth0">
    <REGEXP MODIFIERS="ms">(.*^eth0\s+)(.*?\n\n)(.*)</REGEXP>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="vpnd.conf"            NO="1"      TYPE="FILE"        ACCESS="RW"
        NAME="&vpnd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="vpnd.conf2"            NO="2"      TYPE="FILE"        ACCESS="RW"
        NAME="&vpnd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="ifconfig"             NO="3"      TYPE="COMMAND"     ACCESS="R"
	  NAME="&ifconfig;">
  </HANDLE>

  <HANDLE ID="vpnd_status"          NO="5"     TYPE="COMMAND"     ACCESS="R"
	NAME="&vpnd_status;">
  </HANDLE>

  <HANDLE ID="chkconfig_status"     NO="6"     TYPE="COMMAND"     ACCESS="R"
	NAME="&chkconfig_status;">
  </HANDLE>

  <HANDLE ID="vpnd_switch"          NO="7"     TYPE="COMMAND"     ACCESS="W"
	NAME="&vpnd_switch;">
  </HANDLE>

  <HANDLE ID="chkconfig_switch"     NO="8"     TYPE="COMMAND"     ACCESS="W"
	NAME="&chkconfig_switch;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/WebFrontend/CIMOM/lib/PaulA/Provider/paul/PaulA_Group.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY groups.paula          "/etc/percimon/PaulA/groups.paula"   >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- ****************** -->
  <PROPERTY ID="Permissions">
    <INOUT SECTION="s1" HANDLE="groups.paula">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- ********************* -->
  <!-- **** KEYBINDINGS **** -->
  <!-- ********************* -->

  <KEYBINDINGS>
    <IN HANDLE="groups.paula">
    </IN>
  </KEYBINDINGS>

  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="s1">
    <REGEXP MODIFIERS="ms">(.*?^Group \"$KEY_Name\"\s*\n)(.+?)(^EndGroup$.*)</REGEXP>
  </SECTION>



  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="groups.paula"         NO="1"      TYPE="FILE"        ACCESS="RW"
	  NAME="&groups.paula;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All groups.paula reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->
