=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/provider.dtd
<!-- ******************************************************************* -->
<!--                                                                     -->
<!-- This DTD defines the syntax for provider XML 1.0 documents          -->
<!--                                                                     -->
<!-- Last changes:  2000-11-14                                           -->
<!--                                                                     -->
<!-- ******************************************************************* -->

<!ENTITY % InOutAttribs		"SECTION	CDATA		#IMPLIED
				 HANDLE		CDATA		#REQUIRED
				 FORCE_WRITE	(true|false)	#IMPLIED">

<!ENTITY % InOutDepAttribs	"PROPERTY	CDATA	#REQUIRED">



<!-- ************************************* -->
<!--  Root element                         -->
<!-- ************************************* -->

<!ELEMENT PAULA_CONFIG (DEFINITIONS*,
			PROPERTY*,KEYBINDINGS*,INSTANCE*,SECTION*,HANDLE*)>


<!-- ****************************************** -->
<!--  DEFINITIONS and its elements              -->
<!-- ****************************************** -->

<!ELEMENT DEFINITIONS ((DEFINE)*)>

<!ELEMENT DEFINE (#PCDATA)>
<!ATTLIST DEFINE
	NAME		CDATA		#REQUIRED
>



<!-- ****************************************** -->
<!--  PROPERTY, KEYBINDINGS and their elements  -->
<!-- ****************************************** -->

<!ELEMENT PROPERTY (DEPENDENCIES?,(IN|OUT|INOUT)*)>
<!ATTLIST PROPERTY 
	ID		CDATA		#REQUIRED
	MIGHT_BE_NULL	(true|false)	#IMPLIED
>


<!ELEMENT KEYBINDINGS ((IN|OUT|INOUT)*)>



<!ELEMENT DEPENDENCIES (IN_DEP|OUT_DEP|INOUT_DEP)*>

<!ELEMENT IN_DEP EMPTY>
<!ATTLIST IN_DEP
	%InOutDepAttribs;
>

<!ELEMENT OUT_DEP EMPTY>
<!ATTLIST OUT_DEP
	%InOutDepAttribs;
>

<!ELEMENT INOUT_DEP EMPTY>
<!ATTLIST INOUT_DEP
	%InOutDepAttribs;
>


<!-- ************************************* -->
<!--  IN/OUT/INOUT and their elements      -->
<!-- ************************************* -->

<!ELEMENT IN	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (REGEXP|FUNCTION|INTERNAL)?,
		 (CALL)?)>
<!ATTLIST IN
	%InOutAttribs;
>
<!ELEMENT OUT	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (REGEXP|FUNCTION)?,
		 (CALL)?)>
<!ATTLIST OUT
	%InOutAttribs;
>
<!ELEMENT INOUT	((REQUIRED_ASSIGNMENT|OPTIONAL_ASSIGNMENT|FLAG)?,
		 (FUNCTION|REGEXP)?,
		 (CALL)?)>
<!ATTLIST INOUT
	%InOutAttribs;
>


<!ELEMENT FUNCTION EMPTY>

<!ELEMENT INTERNAL (#PCDATA)>

<!ELEMENT REGEXP (#PCDATA)>
<!ATTLIST REGEXP
	MODIFIERS	CDATA	#IMPLIED
>



<!ELEMENT REQUIRED_ASSIGNMENT EMPTY>

<!ELEMENT OPTIONAL_ASSIGNMENT EMPTY>
<!ATTLIST OPTIONAL_ASSIGNMENT
	DEFAULT			CDATA		#IMPLIED
	TEXT			CDATA		#IMPLIED
	DELETE_IF_DEFAULT	(true|false)	#IMPLIED
>

<!ELEMENT FLAG EMPTY>
<!ATTLIST FLAG
	DEFAULT			CDATA		#IMPLIED
	VALUE			CDATA		#IMPLIED
	TEXT			CDATA		#IMPLIED
>


<!-- ************************************* -->
<!--  SECTION and its elements             -->
<!-- ************************************* -->

<!ELEMENT SECTION (REGEXP,ERROR_NOT_FOUND?)>
<!ATTLIST SECTION
	ID	CDATA	#REQUIRED
>

<!ELEMENT ERROR_NOT_FOUND EMPTY>
<!ATTLIST ERROR_NOT_FOUND
	CODE	CDATA	#REQUIRED
>




<!-- ************************************* -->
<!--  HANDLE and its elements              -->
<!-- ************************************* -->

<!ELEMENT HANDLE (WHITESPACE?,COMMENTS?,REMOVE?,ERROR?,PERMISSIONS?)>
<!ATTLIST HANDLE
	ID	CDATA			#REQUIRED
	NO	CDATA			#REQUIRED
	TYPE	(FILE|COMMAND|DUMMY)	#REQUIRED
	ACCESS	(R|W|RW)		#REQUIRED
	NAME	CDATA			#IMPLIED
>

<!ELEMENT CALL EMPTY>
<!ATTLIST CALL
	OPTION	CDATA		#IMPLIED
>

<!ELEMENT WHITESPACE EMPTY>
<!ATTLIST WHITESPACE
	WRITE	CDATA		#REQUIRED
>

<!ELEMENT COMMENTS (READ.LINE,WRITE.LINE)>

<!ELEMENT READ.LINE (#PCDATA)>
<!ELEMENT WRITE.LINE (#PCDATA)>


<!ELEMENT REMOVE EMPTY>
<!ATTLIST REMOVE
	IF_EMPTY	(true|false)	#IMPLIED
>

<!ELEMENT ERROR EMPTY>
<!ATTLIST ERROR
	ONREAD		(true|false)	#IMPLIED
	ONWRITE		(true|false)	#IMPLIED
>

<!ELEMENT PERMISSIONS EMPTY>
<!ATTLIST PERMISSIONS
	UMASK		CDATA	#IMPLIED
	UID		CDATA	#IMPLIED
	GID		CDATA	#IMPLIED
>

=== durandom/b4wbem/CIMOM/CIMOM/lib/PaulA/Provider/paul/PaulA_User.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY passwd           "/etc/passwd"                              >
<!ENTITY group            "/etc/group"                               >
<!ENTITY rights           "/etc/percimon/PaulA/groups.paula"         >
<!ENTITY virtual          "/etc/postfix/virtual"                     >
<!ENTITY dlists           "/etc/postfix/dlists.virtual"              >
<!ENTITY postmap_dlists   "| postmap /etc/postfix/dlists.virtual"    >
<!ENTITY postmap_aliases  "| postmap /etc/postfix/virtual"           >
<!ENTITY postfix_reload   "| postfix reload"                         >
<!ENTITY webaccess        "/etc/squid/users"                         >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->


  <!-- *************** -->
  <PROPERTY ID="Password">
    <INOUT SECTION="s1" HANDLE="passwd">  <!-- dummy handle, in fact PAM -->
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="RealName">
    
    <IN SECTION="s1" HANDLE="passwd">
      <REQUIRED_ASSIGNMENT/>
      <INTERNAL>(split ':')[4]</INTERNAL>
    </IN>

    <OUT SECTION="s1" HANDLE="passwd">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP>^((?:.*?:){4})(.*?)(:.*)</REGEXP>
    </OUT>

  </PROPERTY>

  <!-- ******************* -->
  <PROPERTY ID="FaxExtensions"
	    MIGHT_BE_NULL="true">
    <INOUT HANDLE="virtual">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- ******************** -->
  <PROPERTY ID="HomeDirectory">
    <INOUT SECTION="s1" HANDLE="passwd">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP>^((?:.*?:){5})(.*?)(:.*)</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ***************** -->
  <PROPERTY ID="LoginShell">

    <IN SECTION="s1" HANDLE="passwd">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </IN>

    <OUT SECTION="s1" HANDLE="passwd">
      <REQUIRED_ASSIGNMENT/>
      <REGEXP>(.*:)(.*?)()$</REGEXP>
    </OUT>

  </PROPERTY>

  <!-- **************** -->
  <PROPERTY ID="WebAccess">
    <INOUT HANDLE="webaccess">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- ********************** -->
  <PROPERTY ID="HasLocalHomepage"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
    </DEPENDENCIES>
    <INOUT HANDLE="dummy">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>


  <!-- ***************** -->
  <PROPERTY ID="MailForward"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
    </DEPENDENCIES>
    <INOUT HANDLE="forward">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="AutoReply"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
    </DEPENDENCIES>
    <INOUT HANDLE="forward">
<!--      <FLAG DEFAULT="0"-->
<!--            VALUE="1"-->
<!--            TEXT="bla" />  -->
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- *************** -->
  <PROPERTY ID="ReplyText"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
    </DEPENDENCIES>
    <INOUT HANDLE="replytext">
    </INOUT>
  </PROPERTY>


  <!-- ****************** -->
  <!-- ** private mail ** -->
  <!-- ****************** -->
  
  <!-- ********************** -->
  <PROPERTY ID="PrivatePopServer"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
      <IN_DEP PROPERTY="PrivatePopLogin" />
      <IN_DEP PROPERTY="PrivatePopPassword" />
      <OUT_DEP PROPERTY="PrivatePopLogin" />
      <OUT_DEP PROPERTY="PrivatePopPassword" />
    </DEPENDENCIES>
    <INOUT HANDLE="fetchmailrc">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>
  
  <!-- ********************* -->
  <PROPERTY ID="PrivatePopLogin"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
      <IN_DEP PROPERTY="PrivatePopPassword" />
      <IN_DEP PROPERTY="PrivatePopServer" />
      <OUT_DEP PROPERTY="PrivatePopPassword" />
      <OUT_DEP PROPERTY="PrivatePopServer" />
    </DEPENDENCIES>
    <INOUT HANDLE="fetchmailrc">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>
  
  <!-- ************************ -->
  <PROPERTY ID="PrivatePopPassword"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="HomeDirectory" />
      <IN_DEP PROPERTY="PrivatePopServer" />
      <IN_DEP PROPERTY="PrivatePopLogin" />
      <OUT_DEP PROPERTY="PrivatePopServer" />
      <OUT_DEP PROPERTY="PrivatePopLogin" />
    </DEPENDENCIES>
    <INOUT HANDLE="fetchmailrc">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>
  


  <!-- ****************** -->
  <PROPERTY ID="MailAliases">
    <INOUT HANDLE="virtual">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="postmap_aliases">
      <FUNCTION/>
    </OUT>
  </PROPERTY>

  <!-- ************************ -->
  <PROPERTY ID="DistributionLists">
    <INOUT HANDLE="dlists">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="postmap_dlists">
      <FUNCTION/>
    </OUT>
  </PROPERTY>



  <!-- ****************** -->
  <PROPERTY ID="PaulAGroups">
    <INOUT HANDLE="group">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- *********************** -->
  <PROPERTY ID="PaulAPermissions">
    <DEPENDENCIES>
      <IN_DEP PROPERTY="PaulAGroups" />
    </DEPENDENCIES>
    <INOUT HANDLE="rights">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>




  <!-- ********************* -->
  <!-- **** KEYBINDINGS **** -->
  <!-- ********************* -->

  <KEYBINDINGS>
    <IN HANDLE="group">
    </IN>
  </KEYBINDINGS>


  <!-- ****************** -->
  <!-- **** INSTANCE **** -->
  <!-- ****************** -->

<!--    <INSTANCE> -->

<!--      <CREATE_INSTANCE> -->
<!--      </CREATE_INSTANCE> -->

<!--    </INSTANCE> -->


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="s1">
    <REGEXP MODIFIERS="ms">(.*)^($KEY_Login:.+?)$(.*)</REGEXP>
    <ERROR_NOT_FOUND CODE="6"/>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="passwd"          NO="1"      TYPE="FILE"        ACCESS="RW"
	  NAME="&passwd;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="group"           NO="3"      TYPE="FILE"        ACCESS="RW"
	  NAME="&group;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>
  
  <HANDLE ID="rights"          NO="4"      TYPE="FILE"        ACCESS="RW"
	  NAME="&rights;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>
  
  <HANDLE ID="virtual"         NO="5"      TYPE="FILE"        ACCESS="RW"
	  NAME="&virtual;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="webaccess"       NO="7"      TYPE="FILE"        ACCESS="RW"
	  NAME="&webaccess;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
    <ERROR ONREAD="false"/>
  </HANDLE>

  <HANDLE ID="forward"         NO="8"      TYPE="FILE"        ACCESS="RW">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
    <ERROR ONREAD="false"/>
  </HANDLE>
  
  <HANDLE ID="replytext"       NO="9"      TYPE="FILE"        ACCESS="RW">
    <ERROR ONREAD="false"/>
  </HANDLE>

  <HANDLE ID="fetchmailrc"     NO="10"     TYPE="FILE"        ACCESS="RW">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
    <REMOVE IF_EMPTY="true"/>
    <ERROR ONREAD="false"/>
  </HANDLE>
  
  <HANDLE ID="dlists"          NO="11"     TYPE="FILE"        ACCESS="RW"
        NAME="&dlists;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="dummy"           NO="12"     TYPE="DUMMY"       ACCESS="RW">
  </HANDLE>

  <HANDLE ID="postmap_dlists"  NO="13"     TYPE="COMMAND"     ACCESS="W"
	NAME="&postmap_dlists;">
  </HANDLE>
  
  <HANDLE ID="postmap_aliases" NO="14"     TYPE="COMMAND"     ACCESS="W"
	NAME="&postmap_aliases;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/test/Test_User.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY passwd          "files/passwd"           >
<!ENTITY group           "files/group"            >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->


  <!-- *************** -->
  <PROPERTY ID="Signature"
	    MIGHT_BE_NULL="true">
    <IN HANDLE="signature">
    </IN>
    <OUT HANDLE="signature">
      <FUNCTION/>
    </OUT>
  </PROPERTY>

  <!-- ****************** -->
  <PROPERTY ID="MailAddress">
    <IN HANDLE="dummy">
      <FUNCTION/>
    </IN>
  </PROPERTY>
  
  <!-- ******************* -->
  <PROPERTY ID="SystemGroups">
    <INOUT HANDLE="group">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>



  <!-- ********************* -->
  <!-- **** KEYBINDINGS **** -->
  <!-- ********************* -->

  <KEYBINDINGS>
    <IN HANDLE="passwd">
    </IN>
  </KEYBINDINGS>



  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="s1">
    <REGEXP MODIFIERS="ms">(.*)^($KEY_Login:.+?)$(.*)</REGEXP>
    <ERROR_NOT_FOUND CODE="6"/>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="passwd"         NO="1"      TYPE="FILE"        ACCESS="RW"
	  NAME="&passwd;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="signature"      NO="2"      TYPE="FILE"        ACCESS="RW">
    <ERROR ONREAD="false"/>
    <PERMISSIONS UMASK="0600" />
  </HANDLE>

  <HANDLE ID="group"          NO="3"      TYPE="FILE"        ACCESS="RW"
	  NAME="&group;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>
  
  <HANDLE ID="dummy"          NO="4"     TYPE="DUMMY"       ACCESS="RW">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/CIMOM/lib/PaulA/Provider/test/PaulA_Instance.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY transport      "files/postfix/transport"   >
<!ENTITY postmap        "| postmap.sh transport"    >
<!ENTITY groups.paula   "files/groups.paula"        >
<!ENTITY group          "files/group"               >
]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <PROPERTY ID="Create_OutgoingMailDomain" MIGHT_BE_NULL="true">
    <INOUT HANDLE="transport">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="postmap">
    </OUT>
  </PROPERTY>

  <PROPERTY ID="Delete_OutgoingMailDomain" MIGHT_BE_NULL="true">
    <INOUT HANDLE="transport">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="postmap">
    </OUT>
  </PROPERTY>

  <PROPERTY ID="Create_Group" MIGHT_BE_NULL="true">
    <INOUT HANDLE="groups.paula">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="group">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </OUT> 
  </PROPERTY>

  <PROPERTY ID="Delete_Group" MIGHT_BE_NULL="true">
    <INOUT HANDLE="groups.paula">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
    <OUT HANDLE="group">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </OUT> 
  </PROPERTY>

  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="transport"           NO="1"      TYPE="FILE"        ACCESS="RW"
        NAME="&transport;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="postmap"              NO="2"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postmap;">
  </HANDLE>

  <HANDLE ID="groups.paula"         NO="3"      TYPE="FILE"        ACCESS="RW"
	  NAME="&groups.paula;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="group"                NO="4"      TYPE="FILE"        ACCESS="RW"
	  NAME="&group;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/paul/PaulA_DHCP.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY dhcpd.conf         "/etc/dhcpd.conf"                   >
<!ENTITY dhcpd_status       "/etc/rc.d/init.d/dhcpd status |"   >
<!ENTITY chkconfig_status   "chkconfig.sh --list dhcpd |"       >
<!ENTITY dhcpd_switch       "| /etc/rc.d/init.d/dhcpd"          >
<!ENTITY chkconfig_switch   "| chkconfig"                       >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->


  <!-- ************* -->
  <PROPERTY ID="Ranges">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="DHCPEnabled" />
    </DEPENDENCIES>
    
    <INOUT SECTION="s1" HANDLE="dhcpd.conf">
      <REQUIRED_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- ****************** -->
  <PROPERTY ID="HostMappings"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="DHCPEnabled" />
    </DEPENDENCIES>
    
    <INOUT SECTION="s1" HANDLE="dhcpd.conf">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- *********************** -->
  <PROPERTY ID="DomainNameServers"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="DHCPEnabled" />
    </DEPENDENCIES>
    
    <INOUT SECTION="s1" HANDLE="dhcpd.conf">
      <OPTIONAL_ASSIGNMENT/>
      <FUNCTION/>
    </INOUT>
  </PROPERTY>

  <!-- ************* -->
  <PROPERTY ID="Routers"
	    MIGHT_BE_NULL="true">
    <DEPENDENCIES>
      <INOUT_DEP PROPERTY="DHCPEnabled" />
    </DEPENDENCIES>
    
    <INOUT SECTION="s1" HANDLE="dhcpd.conf">
      <OPTIONAL_ASSIGNMENT TEXT="\toption routers $VAR;\n"
			   DELETE_IF_DEFAULT="true" />
      <REGEXP>.*(option routers\s+(.+?);).*</REGEXP>
    </INOUT>
  </PROPERTY>

  <!-- ****************** -->
  <PROPERTY ID="DHCPEnabled">
    <IN HANDLE="dhcpd_status">
      <FUNCTION/>
    </IN>
    <IN HANDLE="chkconfig_status">
      <FLAG DEFAULT="0"
	    VALUE="1" />
      <REGEXP MODIFIERS="ms">(.*)(on)(.*)</REGEXP>
    </IN>
    <OUT HANDLE="dhcpd_switch">
      <FUNCTION/>
    </OUT>
    <OUT HANDLE="chkconfig_switch">
      <FUNCTION/>
    </OUT>
  </PROPERTY>


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="s1">
    <REGEXP MODIFIERS="ms">(.*^subnet .+?{)(.*)(^}.*)</REGEXP>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="dhcpd.conf"           NO="1"     TYPE="FILE"        ACCESS="RW"
	  NAME="&dhcpd.conf;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="dhcpd_status"         NO="2"     TYPE="COMMAND"     ACCESS="R"
	NAME="&dhcpd_status;">
    <ERROR ONREAD="false"/>
  </HANDLE>

  <HANDLE ID="chkconfig_status"     NO="3"     TYPE="COMMAND"     ACCESS="R"
	NAME="&chkconfig_status;">
  </HANDLE>

  <HANDLE ID="dhcpd_switch"         NO="4"     TYPE="COMMAND"     ACCESS="W"
	NAME="&dhcpd_switch;">
  </HANDLE>

  <HANDLE ID="chkconfig_switch"     NO="5"     TYPE="COMMAND"     ACCESS="W"
	NAME="&chkconfig_switch;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/CIMOM/lib/PaulA/Provider/test/PaulA_Firewall.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY packetfilter       "files/packetfilter"        >
<!ENTITY restart            "misc.sh reload |"      >   <!-- mark -->

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- **************** -->
  <PROPERTY ID="TelnetEnabled"
	    MIGHT_BE_NULL="true">
    <INOUT SECTION="telnet" HANDLE="packetfilter">
      <FLAG DEFAULT="0"
            VALUE="1"
            TEXT="/etc/packetfilter/telnet" />
      <REGEXP MODIFIERS="ms">(.*^)(/etc/packetfilter/telnet)(.*)</REGEXP>
    </INOUT>
    <OUT HANDLE="restart">
    </OUT>
  </PROPERTY>


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="telnet">
    <REGEXP MODIFIERS="ms">(.*echo\s+"Telnet\s+bla"\n)([^\n]*)(.*)</REGEXP>
  </SECTION>

  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="packetfilter"           NO="1"      TYPE="FILE"        ACCESS="RW"
        NAME="&packetfilter;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="restart"        NO="2"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&restart;">
  </HANDLE>


</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->

=== durandom/b4wbem/WebFrontend/CIMOM/lib/PaulA/Provider/paul/PaulA_OutgoingMailDomain.xml
<!DOCTYPE PAULA_CONFIG SYSTEM "../provider.dtd" [

<!ENTITY transport       "/etc/postfix/transport"            >
<!ENTITY postmap         "| postmap /etc/postfix/transport"  >
<!ENTITY postfix_reload  "| postfix reload"                  >

]>

<PAULA_CONFIG>

  <!-- ******************** -->
  <!-- **** PROPERTIES **** -->
  <!-- ******************** -->

  <!-- ****************** -->
  <PROPERTY ID="ServerName" >
    <IN SECTION="s1" HANDLE="transport">
      <REGEXP MODIFIERS="ms">(.*?^\S+\s*:\[)(\S+)(\]$.*)</REGEXP>
    </IN>
    <OUT SECTION="s1" HANDLE="transport">
      <FUNCTION/>
    </OUT>
    <OUT HANDLE="postmap">
    </OUT>
    <OUT HANDLE="postfix_reload">
    </OUT>
  </PROPERTY>

  <!-- ********************* -->
  <!-- **** KEYBINDINGS **** -->
  <!-- ********************* -->

  <KEYBINDINGS>
    <IN HANDLE="transport">
    </IN>
  </KEYBINDINGS>


  <!-- ****************** -->
  <!-- **** SECTIONS **** -->
  <!-- ****************** -->

  <SECTION ID="s1">
    <REGEXP MODIFIERS="ms">(.*)^($KEY_Domain.*?^\.$KEY_Domain.*?)$(.*)</REGEXP>
  </SECTION>


  <!-- ***************** -->
  <!-- **** HANDLES **** -->
  <!-- ***************** -->

  <HANDLE ID="transport"           NO="1"      TYPE="FILE"        ACCESS="RW"
        NAME="&transport;">
    <WHITESPACE WRITE=" " />
    <COMMENTS>
      <READ.LINE>#</READ.LINE>
      <WRITE.LINE> #</WRITE.LINE>
    </COMMENTS>
  </HANDLE>

  <HANDLE ID="postmap"              NO="2"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postmap;">
  </HANDLE>

  <HANDLE ID="postfix_reload"       NO="3"      TYPE="COMMAND"     ACCESS="W"
	  NAME="&postfix_reload;">
  </HANDLE>

</PAULA_CONFIG>

<!--
Copyright (c) 2000 ID-PRO Deutschland GmbH. All rights reserved.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.
-->
