=== durandom/b4wbem/WebFrontend/WebFrontend/xml/paula.dtd
<!-- ******************************************************************* -->
<!--                                                                     -->
<!-- This DTD defines the syntax for Tree XML 1.0 documents              -->
<!--                                                                     -->
<!-- DTD Version: 1.3                                                    -->
<!-- Date:        Aug 4 2000                                             -->
<!--                                                                     -->
<!-- ******************************************************************* -->


<!-- Definition von externen Referenzen (Entities) -->



<!-- Definition von internen Referenzen (Entities) -->

<!ENTITY	% defAttr	'label CDATA #REQUIRED
				name NMTOKEN #REQUIRED
				cimproperty NMTOKEN #REQUIRED'>





<!-- Definition der Elemente dieser DTD und ihrer Attribute -->


<!ELEMENT paula ( node, form* )>



	<!-- Die Knotenstruktur fuer das Menue -->

<!ELEMENT	node ( node )* >
<!ATTLIST	node
		label CDATA #REQUIRED
	        name CDATA #REQUIRED>


	<!-- Elemente der Formulare -->

<!ELEMENT	form		( docs, components, actions )>
<!ATTLIST	form
		name ID #REQUIRED>

<!ELEMENT	docs		( title, description, help )>

<!ELEMENT	title		( #PCDATA )>
<!ELEMENT	description	( #PCDATA )>
<!ELEMENT	help		( #PCDATA )>


<!ELEMENT	actions		( cimget, cimset, submit, action* )>

<!ELEMENT	cimget		( #PCDATA )>
<!ATTLIST	cimget
		src NMTOKEN #REQUIRED>
<!ELEMENT	cimset		( #PCDATA )>
<!ATTLIST	cimset
		src NMTOKEN #REQUIRED>
<!ELEMENT	submit		EMPTY>
<!ATTLIST	submit
		label CDATA #REQUIRED
		name NMTOKEN #REQUIRED
		method CDATA #REQUIRED>
<!ELEMENT	action		EMPTY>
<!ATTLIST	action
		label CDATA #REQUIRED
		name NMTOKEN #REQUIRED
		method CDATA #REQUIRED>



<!ELEMENT	components	( text | inputfield | inputarea | password | inputtime |inputvalue |
				  singleselect | multipleselect | boolselect |
				  editlist | editIPlist | editMACIPlist |
				  exchangelist | hiddenfield |
				  inputIP
				)* >

<!ELEMENT	text		( #PCDATA )>

<!ELEMENT	inputfield	( #PCDATA )>
<!ATTLIST	inputfield
		%defAttr;>

<!ELEMENT	inputarea	( #PCDATA )>
<!ATTLIST	inputarea
		%defAttr;>

<!ELEMENT	password	EMPTY>
<!ATTLIST	password
		%defAttr;>

<!ELEMENT	inputtime	( #PCDATA )>
<!ATTLIST	inputtime
		%defAttr;>

<!ELEMENT	inputvalue	( #PCDATA )>
<!ATTLIST	inputvalue
		%defAttr;>


<!ELEMENT	singleselect	( default?,choice* )>
<!ATTLIST	singleselect
		%defAttr;>

<!ELEMENT	multipleselect	( default*, choice* )>
<!ATTLIST	multipleselect
		%defAttr;>

<!ELEMENT	boolselect	EMPTY>
<!ATTLIST	boolselect
		%defAttr;
		value CDATA #REQUIRED>

<!ELEMENT	default		(#PCDATA)>
<!ATTLIST	default
		value CDATA #REQUIRED>

<!ELEMENT	choice		(#PCDATA)>
<!ATTLIST	choice
		value CDATA #REQUIRED>


<!ELEMENT	list		( member* )>
<!ATTLIST	list
		%defAttr;>

<!ELEMENT	member		( #PCDATA )>

<!ELEMENT	editlist	( list )>
<!ATTLIST	editlist
		%defAttr;>

<!ELEMENT	editIPlist	( list )>
<!ATTLIST	editIPlist
		%defAttr;>

<!ELEMENT	editMACIPlist	( list )>
<!ATTLIST	editMACIPlist
		%defAttr;>

<!ELEMENT	exchangelist	( list, list )>
<!ATTLIST	exchangelist
		%defAttr;>

<!ELEMENT	inputIP		( #PCDATA )>
<!ATTLIST	inputIP
		%defAttr;>

<!ELEMENT	hiddenfield	EMPTY>
<!ATTLIST	hiddenfield
		name CDATA #REQUIRED
		value CDATA #REQUIRED>

=== durandom/b4wbem/WebFrontend/WebFrontend/xml/paula.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE paula SYSTEM "paula.dtd">

<paula>

<node label="Paula" name="PAULA">
	<node label="Benutzer" name="NODE-USER" cimproperty="MenuUsers">
		<node label="anlegen" name="CREATEUSER" />
		<node label="löschen" name="DELUSER" />
	</node>
	<node label="Internet" name="NODE-INTERNET">
		<node label="Filter" name="FILTER"/>
		<node label="Providerdaten" name="PROVIDERDATA"/>
		<node label="Netzdaten" name="NETDATA"/>
	</node>
	<node label="System" name="NODE-SYSTEM">
		<node label="Reboot" name="REBOOT"/>
		<node label="Halt" name="HALT"/>
	</node>
	<node label="Mail" name="NODE-MAIL">
		<node label="Eingang" name="NODE-RECEIVE" cimproperty="AllIncomingServers">
			<node label="einrichten" name="CREATEMAILSERVERIN"/>
			<node label="löschen" name="DELETEMAILSERVERIN"/>
		</node>
		<node label="Ausgang" name="NODE-SEND" cimproperty="AllOutgoingDomains">
			<node label="einrichten" name="CREATEDOMAIN"/>
			<node label="löschen" name="DELETEDOMAIN"/>
			<node label="Standard" name="DEFAULTMAILSERVEROUT"/>
		</node>
		<node label="Abhol-Intervall" name="GETINTERVAL"/>
		<node label="Mail manuell abholen" name="GETMAIL"/>
	</node>
	<node label="Fax" name="FAX"/>
	<node label="VPN" name="VPN"/>
	<node label="RAS" name="NODE-RAS">
		<node label="anlegen" name="CREATERAS"/>
		<node label="löschen" name="DELETERAS"/>
		<node label="Schmidt" name="RASUSER"/>
		<node label="Jacobs" name="RASUSER"/>
		<node label="Janssen" name="RASUSER"/>
		<node label="Schneider" name="RASUSER"/>
	</node>
	<node label="Mailverteiler" name="ADMINMAILINGLISTS"/>
	<node label="DHCP" name="NODE-DHCP">
		<node label="DHCP aktivieren" name="DHCPACTIVATE"/>
		<node label="DNS einrichten" name="DNSSERVER"/>
		<node label="IP-Adressen" name="IPADDRESSES"/>
		<node label="Statische Adressen" name="STATICADDRESSES"/>
		<node label="Standard Gateway" name="DEFGATEWAY"/>
	</node>
	<node label="Intranet" name="INTRANET"/>
	<node label="Firewall" name="FIREWALL"/>
	<node label="Statistiken" name="WEBSTATISTICS"/>
	<node label="Paul Administration" name="NODE-PAULADMIN">
		<node label="Konfiguration" name="NODE-PAULCONF">
			<node label="Backup einspielen" name="UPLOADSETTINGS"/>
			<node label="Backup erstellen" name="DOWNLOADSETTINGS"/>
			<node label="Intervall" name="BACKUPSETTINGS"/>
		</node>
		<node label="Datenbackups" name="NODE-DATABACKUP">
			<node label="einspielen" name="UPLOADDATABACKUP"/>
			<node label="erstellen" name="DOWNLOADDATABACKUP"/>
		</node>
		<node label="Gruppen" name="NODE-GROUPRIGHTS" cimproperty="AllGroups">
			<node label="anlegen" name="CREATEGROUP"/>
			<node label="löschen" name="DELETEGROUP"/>
		</node>
		<node label="globale Aliase" name="GLOBALALIASES"/>
		<node label="Paul aktualisieren" name="UPDATEPAUL"/>
		<node label="Systemeinstellungen" name="SYSTEMSETTINGS"/>
	</node>
	<node label="Logout" name="LOGOUT"/>
</node>


  <!-- ___Create Group___________________________________________________ -->
  <form name="CREATEGROUP" label="Paul Administration/Gruppen/anlegen" group="PAULADMIN/GROUPS">

    <docs>
      <title>Gruppe anlegen</title>
      <description>Mit diesem Formular können Sie eine neue Gruppe anlegen.</description>
      <help name="NewPaulAGroup">Zu welcher Paula-Gruppe soll der neue User gehören?</help>
    </docs>

    <components>
      <inputfield label="Name der Gruppe" name="Create_Group" cimproperty="Create_Group" choosefrom="nothing"/>
      <permissionlist label="Rechte dieser Gruppe an folgenden Formularen" name="NewPermissions" cimproperty="NewPermissions" choosefrom="Permissions" mandatory=""/>
    </components>

    <actions>
      <cimget/>
      <cimset/>
      <submit label="Anlegen" name="submit" />
      <reset label="Reset" name="reset" />
    </actions>

  </form>
  <!-- ___Create Group___________________________________________________ -->

  

  <!-- ___Delete Group___________________________________________________ -->
  <form name="DELETEGROUP" label="Paul Administration/Gruppen/löschen" group="PAULADMIN/GROUPS">
    <docs>
      <title>Gruppe löschen</title>
      <description>Mit diesem Formular können Sie Gruppen löschen</description>
      <help name="DeleteGroup">Hier können Sie die Gruppe auswählen, die gelöscht werden soll</help>
    </docs>

    <components>
      <singleselect label="Gruppe auswählen" name="Delete_Group" cimproperty="Delete_Group" choosefrom="AllGroups"/>
    </components>

    <actions>
      <cimget>
      </cimget>
      <cimset>
      </cimset>
      <submit label="Löschen" name="submit" />
      <reset label="Reset" name="reset" />
    </actions>
  </form>
  <!-- ___Delete Group___________________________________________________ -->

  






  <!-- ___Create User____________________________________________________ -->
  <form name="CREATEUSER" label="Benutzer/anlegen" group="USER">

    <docs>
      <title>Benutzer anlegen</title>
      <description>Mit diesem Formular können Sie die Benutzer administrieren.</description>
      <help name="NewRealName">Der Vor- und Zuname</help>
      <help name="NewLogin">Der Login Name</help>
      <help name="NewPassword">Das Passwort</help>
      <help name="NewPaulAGroup">Zu welcher Paula-Gruppe soll der neue User gehören?</help>
    </docs>

    <components>
      <inputfield label="Benutzername:" name="NewRealName" cimproperty="NewRealName" choosefrom="nothing"/>
      <inputfield label="Login Name:" name="NewLogin" cimproperty="NewLogin" choosefrom="nothing"/>
      <password label="Passwort:" name="NewPassword" cimproperty="NewPassword" choosefrom="nothing"/>
      <singleselect label="Gruppe:" name="NewPaulAGroup" cimproperty="NewPaulAGroup" choosefrom="AllGroups">
      </singleselect>
    </components>

    <actions>
      <cimget/>
      <cimset/>
      <submit label="Ok" name="submit" />
      <reset label="Reset" name="reset" />
    </actions>

  </form>
  <!-- ___Create User____________________________________________________ -->

  

  <!-- ___Delete User____________________________________________________ -->
  <form name="DELUSER" label="Benutzer/löschen" group="USER">
    <docs>
      <title>Benutzer löschen</title>
      <description>Mit diesem Formular können Sie die Benutzer löschen</description>
      <help name="DeleteUser">
          Hier können Sie den Benutzer auswählen, der gelöscht werden soll.
      </help>
    </docs>

    <components>
      <singleselect label="Benutzer auswählen" name="DeleteUser" cimproperty="DeleteUser" choosefrom="AllUsers">
      </singleselect>
    </components>

    <actions>
      <cimget>
      </cimget>
      <cimset>
      </cimset>
      <submit label="Ok" name="submit" />
      <reset label="Reset" name="reset" />
    </actions>
  </form>
  <!-- ___Delete User____________________________________________________ -->

  
  <!-- ___Login__________________________________________________________ -->
  <form name="USERLOGIN" label="Benutzer/Login" group="USER">

    <docs>
      <title cimproperty="Login">Login-Daten für Benutzer </title>
      <description>Mit diesem Formular können Sie die Einstellungen für den User verändern.</description>
      <help name="RealName">Der tatsächliche Name des Benutzers</help>
      <help name="Password">Das System-Passwort</help>
    </docs>

    <components>
      <inputfield label="Benutzername" name="RealName" cimproperty="RealName"/>
      <password label="Passwort" name="Password" cimproperty="Password"/>
    </components>

    <actions>
	<cimget>
	</cimget>	
      <cimset>
      </cimset>
      <submit label="Ok" name="SUBMIT"/>
      <reset label="Reset" name="reset" />
    </actions>
  </form>
  <!-- ___Login__________________________________________________________ -->

  
  <!-- ___FAX-Durchwahlnummern___________________________________________ -->
  <form name="USERFAX" label="Benutzer/Faxdurchwahl" group="USER">

    <docs>
      <title cimproperty="Login">Fax-Durchwahlnummern von </title>
      <description>Geben Sie hier die Durchwahlnummern für Faxe an</description>
      <help name="FaxNumberList">Sie können hier Durchwahlnummern aus der rechten Auswahlliste in die linke kopieren und damit diesem Benutzer zuweisen.</help>
    </docs>

    <components>
      <exchangelist label="" name="FaxNumberList">
	<list label="Fax-Durchwahlnummern" name="FaxExtensions" cimproperty="FaxExtensions"/>
	<list label="Gültige Fax-Nummern" name="ValidFaxExtensions" cimproperty="ValidFaxExtensions"/>
      </exchangelist>
    </components>

    <actions>
	<cimget>
	</cimget>	
      <cimset>
      </cimset>
      <submit label="Ok" name="SUBMIT"/>
      <reset label="Reset" name="reset" />
    </actions>
  </form>
  <!-- ___FAX-Durchwahlnummern___________________________________________ -->

  
  <!-- ___Gruppen_________________________________________________________ -->
  <form name="USERGROUPS" label="Benutzer/Gruppen" group="USER">
    <docs>
      <title>Gruppen</title>
      <description>Hier können Sie Ihre Gruppenzugehörigkeit bearbeiten.</description>
      <help name="usergroups">
          Hier können Sie Ihre Gruppenzugehörigkeit bearbeiten.
      </help>
    </docs>

    <components>
      <exchangelist label="" name="usergroups">
	<list label="Mitglied in" name="PaulAGroups" cimproperty="PaulAGroups"/>
	<list label="Alle Gruppen" name="AllGroups" cimproperty="AllGroups"/>
      </exchangelist>
    </components>

    <actions>
      <cimget>
      </cimget>
      <cimset/>
      <submit label="Ok" name="SUBMIT"/>
      <reset label="Reset" name="reset" />
    </actions>

  </form>
  <!-- ___Gruppen_________________________________________________________ -->



  <!-- ___Mail-Aliase_____________________________________________________ -->
  <form name="USERMAIL" label="Benutzer/Mail-Aliase" group="USER">

    <docs>
      <title>Mail-Aliase</title>
      <description>Hier können Sie Aliase eintragen, unter denen Sie auch erreichbar sind.</description>
